# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import time
import uuid
from typing import Optional

from google import genai
from google.adk.tools import ToolContext
from google.cloud import storage
from google.genai import types

# Hardcoded constants to avoid project number issues on Agent Platform
GCP_PROJECT_ID = "qwiklabs-gcp-03-c10839d3f1ce"
GCS_BUCKET_NAME = "wealthorbit-media-qwiklabs-gcp-03-c10839d3f1ce"
MODEL_NAME = "gemini-3.1-flash-lite-image"
LOCATION = "global"


async def generate_portfolio_milestone_image(
    prompt: str,
    title: str = "Portfolio Milestone",
    tool_context: Optional[ToolContext] = None,
) -> str:
    """Generate an infographic badge or visual card for a portfolio milestone, achievement, or goal.

    The generated image is:
    1. Saved via tool_context.save_artifact so it displays in the Playground Artifacts panel.
    2. Uploaded directly to the public Cloud Storage bucket and returned as an embeddable public HTTPS URL.

    Args:
        prompt: Visual prompt describing the milestone (e.g. 'Sleek luxury gold badge with 100K Net Worth milestone reached').
        title: Short title for the milestone or card (e.g. '100K_Net_Worth', 'Retirement_Goal_Achieved').
        tool_context: ToolContext injected automatically by ADK to manage artifacts and session state.

    Returns:
        JSON string containing the public HTTPS URL, artifact filename, and status.
    """
    try:
        # 1. Generate image using gemini-3.1-flash-lite-image in global region
        client = genai.Client(vertexai=True, project=GCP_PROJECT_ID, location=LOCATION)
        response = await client.aio.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
        )

        image_bytes = None
        mime_type = "image/jpeg"

        if response.candidates and response.candidates[0].content:
            for part in response.candidates[0].content.parts:
                if getattr(part, "inline_data", None) and getattr(part.inline_data, "data", None):
                    image_bytes = part.inline_data.data
                    mime_type = getattr(part.inline_data, "mime_type", mime_type)
                    break

        if not image_bytes:
            return json.dumps({
                "status": "error",
                "message": "No image data was generated by the model."
            })

        extension = "jpg" if "jpeg" in mime_type else "png"
        timestamp = int(time.time())
        unique_id = uuid.uuid4().hex[:6]
        safe_title = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in title.lower())
        filename = f"{safe_title}_{timestamp}_{unique_id}.{extension}"

        # 2. Save artifact using tool_context so it appears in the Playground's Artifacts panel
        artifact_version = None
        if tool_context:
            artifact_part = types.Part.from_bytes(data=image_bytes, mime_type=mime_type)
            artifact_version = await tool_context.save_artifact(
                filename=filename,
                artifact=artifact_part,
                custom_metadata={"title": title, "prompt": prompt}
            )

        # 3. Upload bytes to public Cloud Storage bucket without writing to local disk
        storage_client = storage.Client(project=GCP_PROJECT_ID)
        bucket = storage_client.bucket(GCS_BUCKET_NAME)
        blob = bucket.blob(f"milestones/{filename}")
        blob.upload_from_string(image_bytes, content_type=mime_type)

        public_url = f"https://storage.googleapis.com/{GCS_BUCKET_NAME}/milestones/{filename}"

        return json.dumps({
            "status": "success",
            "title": title,
            "filename": filename,
            "public_url": public_url,
            "artifact_version": artifact_version,
            "message": "Milestone image successfully generated, saved to artifacts, and uploaded to Cloud Storage."
        }, indent=2)

    except Exception as e:
        return json.dumps({
            "status": "error",
            "message": f"Failed to generate milestone image: {str(e)}"
        })
